services:
  avatars:
    build: .
    env_file: .env
    restart: unless-stopped
    init: true
    hostname: avatars.containers.local
    labels:
      - "hostname=avatars.containers.local"
    volumes:
      - ./data:/app/data
  redis:
    image: redis:8.6.2-alpine
    restart: unless-stopped
    init: true
    hostname: redis.avatars.containers.local
    labels:
      - "hostname=redis.avatars.containers.local"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.56/29
    driver_opts:
      com.docker.network.bridge.name: br-avatars
