name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'yiffspace'
    needs: [lint]
    steps:
      - name: Publish to ghcr
        uses: e621ng/publish-to-ghcr@v1
